apiVersion: apps/v1
kind: Deployment
metadata:
 name: monitor-deployment
 labels:
  app: monitor
spec:
 replicas: 3
 selector:
  matchLabels:
   app: monitor
 template:
  metadata:
   labels:
    app: monitor
  spec:
   containers:
   - name: monitor
     image: aron4226/monitor:1.0
     imagePullPolicy: Always
     ports:
     - containerPort: 8080
     env:
     - name: APP_VERSION
       value: "1.0"
     livenessProbe:
      httpGet:
       path: /health/live
       port: 8080
      initialDelaySeconds: 10
      periodSeconds: 10
     readinessProbe:
      httpGet:
       path: /health/ready
       port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
     resources:
      requests:
       memory: "64Mi"
       cpu: "100m"
      limits:
       memory: "128Mi"
       cpu: "200m"